'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, CalendarDays, Download, Printer, Search, UserPlus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { cn } from '@/lib/utils'
import { existingPatients, type ExistingPatient } from '@/lib/registration-data'

export function PatientProfile({ patient, center, generatedMR }: { patient: ExistingPatient | null; center: string; generatedMR: string }) {
  const router = useRouter()
  const p = patient ?? { mr: generateMR('nutrition', []) as any, name: 'New Patient', age: 0, gender: 'Not specified', bloodGroup: 'Not recorded', mobile: 'Not recorded', lastVisit: 'First visit', visits: [], bills: [], parentName: '', city: '', dob: '', address: '' } as ExistingPatient
  const print = () => openA4Print('Patient Details', p, center)
  const effectiveMR = generatedMR || p.mr
  const goBack = () => router.back()
  const createVisit = () => router.push('/visits')
  return <div className="grid gap-6 xl:grid-cols-[280px_1fr]"><aside><Card className="sticky top-20 rounded-lg shadow-sm"><CardContent className="p-5"><div className="flex size-16 items-center justify-center rounded-full bg-primary/10 text-xl font-semibold text-primary">{p.name.split(' ').map((part) => part[0]).join('')}</div><h2 className="mt-4 font-display text-xl font-semibold">{p.name}</h2><p className="mt-1 text-sm text-muted-foreground">{effectiveMR}</p><dl className="mt-6 space-y-3 border-t pt-5 text-sm"><Info label="Age / Gender" value={`${p.age || '—'} / ${p.gender}`}/><Info label="Blood group" value={p.bloodGroup}/><Info label="Phone" value={p.mobile}/><Info label="City" value={p.city}/><Info label="Last visit" value={p.lastVisit}/></dl><div className="mt-6 flex flex-col gap-2"><Button className="w-full" size="sm" onClick={createVisit}><CalendarDays className="mr-2 size-4"/>Create visit</Button><Button variant="outline" size="sm" className="w-full" onClick={goBack}><ArrowLeft className="mr-2 size-4"/>Back</Button></div></CardContent></Card></aside><main><div className="mb-4 flex flex-wrap justify-between gap-2"><div><h2 className="font-display text-xl font-semibold">Patient profile</h2><p className="mt-1 text-sm text-muted-foreground">{center} · Active outpatient record</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={print}><Printer className="mr-2 size-4"/>Print</Button><Button variant="outline" size="sm" onClick={print}><Download className="mr-2 size-4"/>Export PDF</Button></div></div><Tabs defaultValue="overview"><div className="overflow-x-auto"><TabsList className="h-10 bg-muted/70"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="visits">Visits</TabsTrigger><TabsTrigger value="op">OP Sheet</TabsTrigger><TabsTrigger value="prescriptions">Prescriptions</TabsTrigger><TabsTrigger value="documents">Documents</TabsTrigger></TabsList></div><TabsContent value="overview" className="mt-5"><Overview patient={p}/></TabsContent><TabsContent value="visits" className="mt-5"><Visits patient={p}/></TabsContent><TabsContent value="op" className="mt-5"><OPSheet patient={p} center={center}/></TabsContent><TabsContent value="prescriptions" className="mt-5"><Prescription patient={p} center={center}/></TabsContent><TabsContent value="documents" className="mt-5"><Documents patientMR={effectiveMR}/></TabsContent></Tabs></main></div>
}
function Info({ label, value, strong }: { label: string; value: string; strong?: boolean }) { return <div className="flex justify-between gap-3"><dt className="text-muted-foreground">{label}</dt><dd className={cn('text-right font-medium', strong && 'text-destructive')}>{value}</dd></div> }
function Overview({ patient }: { patient: ExistingPatient }) { return <div className="grid gap-5 lg:grid-cols-2"><Section title="Clinical summary"><div className="space-y-4 text-sm"><Info label="Primary center" value="Nutrition Center"/><Info label="Allergies" value={patient?.allergies || 'Not recorded'}/><Info label="Chronic conditions" value={patient?.conditions || 'Not recorded'}/><Info label="Current medications" value={patient?.medications || 'Not recorded'}/></div></Section><Section title="Care activity"><div className="grid grid-cols-3 gap-3"><Metric label="Visits" value={String(patient.visits.length)} /><Metric label="Prescriptions" value="0" /><Metric label="Documents" value="0" /></div></Section><div className="lg:col-span-2"><Visits patient={patient}/></div></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-muted p-3"><p className="text-lg font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div> }
function Visits({ patient }: { patient: ExistingPatient }) { return <Card className="rounded-lg shadow-sm"><CardHeader><CardTitle>Visit history</CardTitle></CardHeader><CardContent>{patient.visits.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y bg-muted/40 text-xs text-muted-foreground"><tr><th className="p-3 font-medium">Visit</th><th className="p-3 font-medium">Date</th><th className="p-3 font-medium">Department</th><th className="p-3 font-medium">Clinician</th><th className="p-3 font-medium">Reason</th></tr></thead><tbody>{patient.visits.map((visit) => <tr className="border-b" key={visit.id}><td className="p-3 font-medium">{visit.id}</td><td className="p-3">{visit.date}</td><td className="p-3">{visit.center}</td><td className="p-3">{visit.doctor}</td><td className="p-3">{visit.reason}</td></tr>)}</tbody></table></div> : <EmptyState title="No visits recorded" action="Create first visit"/>}</CardContent></Card> }
function OPSheet({ patient, center }: { patient: ExistingPatient; center: string }) {
  const [saved, setSaved] = useState(false)
  const [editing, setEditing] = useState(false)
  const [clinicalNotes, setClinicalNotes] = useState('')
  const [investigations, setInvestigations] = useState('')
  const [treatmentPlan, setTreatmentPlan] = useState('')
  return <div className="print-sheet space-y-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-display text-xl font-semibold">Out Patient Registration Sheet</h3><p className="text-sm text-muted-foreground">{patient.name} · {patient.mr}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => openA4Print('OP Registration Sheet', patient, center)}><Printer className="mr-2 size-4"/>Print</Button><Button size="sm" variant="outline" onClick={() => openA4Print('OP Registration Sheet', patient, center)}><Download className="mr-2 size-4"/>Export PDF</Button>{!editing ? <Button size="sm" variant="outline" onClick={() => setEditing(true)}><Pencil className="mr-2 size-4"/>Edit</Button> : <><Button size="sm" variant="outline" onClick={() => { setEditing(false) }}>Cancel</Button><Button size="sm" onClick={() => { setSaved(true); setEditing(false) }}>{saved ? <><Check className="mr-2 size-4"/>Updated</> : 'Update'}</Button></>}<Button size="sm" onClick={() => setSaved(true)}>{saved ? <><Check className="mr-2 size-4"/>Saved</> : 'Save'}</Button></div></div><Section title="Clinical examination" description="Detailed clinical notes"><Textarea className={cn('min-h-48 resize-y', editing && 'ring-2 ring-primary/50')} placeholder="Document clinical examination findings, assessment and observations..." value={clinicalNotes} onChange={(e) => setClinicalNotes(e.target.value)} readOnly={!editing}/></Section><Section title="Baseline measurements" description="Record and compare treatment progress"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr>{['Measurement','Baseline','1 Month','2 Months','3 Months','Change'].map((x) => <th className="p-2 text-left font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{measurements.map((measurement) => <tr className="border-b" key={measurement}><td className="p-2 font-medium">{measurement}</td>{Array.from({length: 5}, (_, i) => <td className="p-1.5" key={i}><Input className="h-7 min-w-24" readOnly={!editing} aria-label={`${measurement} value`}/></td>)}</tr>)}</tbody></table></div></Section><div className="grid gap-5 md:grid-cols-2"><Section title="Investigations"><Textarea className={cn('min-h-24', editing && 'ring-2 ring-primary/50')} placeholder="Test, finding and date" value={investigations} onChange={(e) => setInvestigations(e.target.value)} readOnly={!editing}/></Section><Section title="Treatment plan & follow-up"><Textarea className={cn('min-h-24', editing && 'ring-2 ring-primary/50')} placeholder="Plan, medication, follow-up schedule" value={treatmentPlan} onChange={(e) => setTreatmentPlan(e.target.value)} readOnly={!editing}/></Section></div>{saved && <p className="text-xs text-primary">OP Sheet {editing ? 'updated' : 'saved'} successfully.</p>}</div>
}
function Prescription({ patient, center }: { patient: ExistingPatient; center: string }) {
  const doctorName = 'Dr. Consulting Physician'
  return <div className="print-sheet"><div className="flex items-start justify-between border-b-2 border-primary pb-5"><ClinicHeader center={center}/><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => openA4Print('Prescription', patient, center)}><Printer className="mr-2 size-4"/>Print</Button><Button variant="outline" size="sm" onClick={() => openA4Print('Blank Prescription', null, center)}><FileText className="mr-2 size-4"/>Blank sheet</Button></div></div><div className="rounded-lg border bg-muted/30 p-4 text-sm"><div className="grid gap-2 sm:grid-cols-2"><p><b>Patient:</b> {patient.name}</p><p><b>MR No:</b> {patient.mr}</p><p><b>Age / Sex:</b> {patient.age} / {patient.gender}</p><p><b>DOB:</b> {patient.dob || '—'}</p><p><b>Blood Group:</b> {patient.bloodGroup || '—'}</p><p><b>Mobile:</b> {patient.mobile}</p><p className="sm:col-span-2"><b>Address:</b> {patient.address || patient.city || '—'}</p><p><b>Date:</b> {new Date().toLocaleDateString()}</p><p><b>Doctor:</b> {doctorName}</p></div></div><Section title="Diagnosis"><Textarea placeholder="Clinical diagnosis"/></Section><div className="mt-5"><Section title="Prescription"><table className="w-full text-sm"><thead className="bg-muted text-xs text-muted-foreground"><tr>{['Medicine','Dosage','Frequency','Duration','Instructions'].map((x) => <th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{[1,2,3].map((n) => <tr key={n} className="border-b">{[1,2,3,4,5].map((x) => <td key={x} className="p-2"><Input className="h-7" aria-label={`Prescription row ${n}`}/></td>)}</tr>)}</tbody></table></Section></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Section title="Advice"><Textarea className="min-h-24"/></Section><Section title="Follow-up"><Field label="Next visit" type="date" value="" onChange={() => {}}/></Section></div><div className="mt-16 grid grid-cols-2 gap-10 text-center text-sm"><div className="border-t pt-2">Doctor signature</div><div className="border-t pt-2">Dietitian signature</div></div><div className="mt-8 border-t pt-3 text-center text-xs text-muted-foreground">NEW YOU & Ayurcare Center · Jubilee Bazar, Onden Road, Kannur - 670001, Kerala · PH: 8111999581 / 8111999582</div></div>
}

function generateMR(center: 'nutrition' | 'ayurcare', patients: ExistingPatient[]): string {
  const prefix = center === 'nutrition' ? 'NU' : 'AY'
  const maxNum = patients
    .filter((p) => p.mr.startsWith(prefix))
    .reduce((max, p) => {
      const num = parseInt(p.mr.replace(prefix, ''), 10)
      return isNaN(num) ? max : Math.max(max, num)
    }, 0)
  return `${prefix}${String(maxNum + 1).padStart(6, '0')}`
}

function ClinicHeader({ center }: { center: string }) {
  const nutrition = center.toLowerCase().includes('nutrition')
  return <div><h3 className="font-display text-2xl font-semibold">{nutrition ? 'NEW YOU' : 'Ayurcare Center'}</h3>{nutrition && <p className="mt-1 text-sm font-medium text-primary">Lose Weight. Choose Health.</p>}<p className="mt-1 text-xs text-muted-foreground">{nutrition ? 'Centre for Professional Weight Management' : 'Jubilee Bazar'}<br/>Onden Road, Kannur - 670001, Kerala<br/>PH: 8111999581 / 8111999582</p></div>
}

function Documents({ patientMR }: { patientMR: string }) {
  const [documents, setDocuments] = useState<{ title: string; category: string; date: string; remarks: string; file?: File }[]>([])
  const [title, setTitle] = useState('')
  const [category, setCategory] = useState('Clinical report')
  const [file, setFile] = useState<File | null>(null)
  const add = () => {
    if (!title.trim()) return
    setDocuments((items) => [...items, { title, category, date: new Date().toLocaleDateString(), remarks: 'Uploaded by current staff', file: file || undefined }])
    setTitle(''); setFile(null)
  }
  return <Card className="rounded-lg shadow-sm"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Documents</CardTitle><CardDescription>Clinical reports, scans, images, and supporting records.</CardDescription></div></CardHeader><CardContent><div className="mb-5 grid gap-3 md:grid-cols-[1fr_180px_1fr]"><Input placeholder="Document title" value={title} onChange={(e) => setTitle(e.target.value)}/><select className="h-8 rounded-lg border border-input bg-background px-2.5 text-sm" value={category} onChange={(e) => setCategory(e.target.value)}><option>Clinical report</option><option>Lab report</option><option>Prescription</option><option>Identity document</option><option>Scanned report</option></select><div><Input type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" onChange={(e) => { if (e.target.files?.[0]) setFile(e.target.files[0]) }}/><p className="mt-1 text-xs text-muted-foreground">PDF, Images, Word</p></div></div><div className="flex justify-end"><Button size="sm" onClick={add} disabled={!title.trim()}><Upload className="mr-2 size-4"/>Upload document</Button></div>{documents.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-150 text-sm"><thead className="border-y bg-muted/40 text-xs text-muted-foreground"><tr><th className="p-3 text-left">Title</th><th className="p-3 text-left">Category</th><th className="p-3 text-left">File</th><th className="p-3 text-left">Uploaded</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{documents.map((document, index) => <tr key={`${document.title}-${index}`} className="border-b"><td className="p-3 font-medium">{document.title}</td><td className="p-3">{document.category}</td><td className="p-3">{document.file ? document.file.name : '—'}</td><td className="p-3">{document.date}</td><td className="p-3 text-right"><Button variant="ghost" size="sm">View</Button><Button variant="ghost" size="sm">Download</Button><Button variant="ghost" size="sm" onClick={() => setDocuments((items) => items.filter((_, i) => i !== index))}>Delete</Button></td></tr>)}</tbody></table></div> : <div className="mt-4 rounded-lg border border-dashed py-10 text-center"><FileText className="mx-auto size-6 text-muted-foreground"/><p className="mt-3 font-medium">No documents added</p><p className="mt-1 text-sm text-muted-foreground">Add a title, select a category, choose a file, then upload.</p></div>}</CardContent></Card>
}

function openA4Print(title: string, patient: ExistingPatient | null, center: string) {
  const printWindow = window.open('', '_blank', 'noopener,noreferrer')
  if (!printWindow) return
  const nutrition = center.toLowerCase().includes('nutrition')
  const clinic = nutrition ? 'NEW YOU' : 'Ayurcare Center'
  const subtitle = nutrition ? 'Lose Weight. Choose Health. | Centre for Professional Weight Management' : 'Jubilee Bazar'
  const patientInfo = patient ? `<div class="patient"><div><b>Patient:</b> ${patient.name}</div><div><b>MR No:</b> ${patient.mr}</div><div><b>Age / Gender:</b> ${patient.age} / ${patient.gender}</div><div><b>DOB:</b> ${patient.dob || '—'}</div><div><b>Blood Group:</b> ${patient.bloodGroup || '—'}</div><div><b>Mobile:</b> ${patient.mobile}</div><div><b>Address:</b> ${patient.address || patient.city || '—'}</div><div><b>Date:</b> ${new Date().toLocaleDateString()}</div></div>` : '<div class="patient"><div><b>Patient:</b> ____________________</div><div><b>MR No:</b> ____________________</div><div><b>Age / Gender:</b> ____________________</div><div><b>Date:</b> ____________________</div></div>'
  printWindow.document.write(`<!doctype html><html><head><title>${title}</title><style>@page{size:A4 portrait;margin:14mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#17202a;font-size:12px}.header{border-bottom:2px solid #167b91;padding-bottom:12px;margin-bottom:16px}.clinic{font-size:26px;font-weight:700;color:#167b91}.tag{font-weight:600;margin:4px 0}.address{color:#4b5563;line-height:1.5}.title{font-size:16px;font-weight:700;text-transform:uppercase;margin:18px 0 10px}.patient{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;padding:10px;border:1px solid #b8c7cc;background:#f7fafb}.section{margin-top:18px}.rule{border-bottom:1px solid #b8c7cc;height:34px}.table{width:100%;border-collapse:collapse;margin-top:8px}.table th,.table td{border:1px solid #b8c7cc;padding:8px;text-align:left}.table th{background:#edf5f6}.signature{display:grid;grid-template-columns:1fr 1fr;gap:80px;margin-top:100px;text-align:center}.signature div{border-top:1px solid #17202a;padding-top:8px}@media print{body{margin:0}}</style></head><body><header class="header"><div class="clinic">${clinic}</div><div class="tag">${subtitle}</div><div class="address">Onden Road, Kannur - 670001, Kerala<br>PH: 8111999581 / 8111999582</div></header><div class="title">${title}</div>${patientInfo}<section class="section"><b>Diagnosis / Clinical Notes</b><div class="rule"></div><div class="rule"></div></section><section class="section"><b>${title.includes('Prescription') ? 'Medicines' : 'Clinical Examination'}</b><table class="table"><thead><tr><th>Item</th><th>Dosage / Finding</th><th>Frequency / Notes</th><th>Duration</th></tr></thead><tbody>${Array.from({length: 7}, () => '<tr><td>&nbsp;</td><td></td><td></td><td></td></tr>').join('')}</tbody></table></section><section class="section"><b>Advice and Follow-up</b><div class="rule"></div><div class="rule"></div></section><div class="signature"><div>Doctor Signature</div><div>Dietitian Signature</div></div></body></html>`)
  printWindow.document.close()
  printWindow.focus()
  printWindow.print()
}
function Section({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) {
  return <Card className="rounded-lg shadow-sm"><CardHeader className="border-b pb-4"><CardTitle className="text-base">{title}</CardTitle>{description && <CardDescription className="text-xs">{description}</CardDescription>}</CardHeader><CardContent className="pt-5">{children}</CardContent></Card>
}
function EmptyState({ title, action }: { title: string; action: string }) { return <div className="py-8 text-center"><p className="font-medium">{title}</p><Button size="sm" variant="outline" className="mt-3"><UserPlus className="mr-2 size-4"/>{action}</Button></div> }
