'use client'

import { useState } from 'react'
import { Download, Pencil, Plus, Printer, Search, Trash2, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'

const nutritionRows = [{mr:'NU000001',name:'Aarav Sharma',phone:'98450 12345',plan:'Diabetes nutrition plan',clinician:'Dr. Neha Verma',review:'16 Jul 2026',status:'Due'},{mr:'NU000002',name:'Priya Nair',phone:'99860 45678',plan:'Weight management',clinician:'Dr. Neha Verma',review:'18 Jul 2026',status:'Active'}]
const ayurRows = [{mr:'AY000001',name:'Rohan Mehta',phone:'90080 33221',plan:'Panchakarma program',clinician:'Dr. Arjun Das',review:'14 Jul 2026',status:'Active'},{mr:'AY000002',name:'Anjali Menon',phone:'98765 21430',plan:'Herbal therapy',clinician:'Dr. Arjun Das',review:'17 Jul 2026',status:'Planned'}]

export function CareWorkspace({ kind }: { kind: 'nutrition' | 'ayurcare' }) {
  const nutrition = kind === 'nutrition'
  const title = nutrition ? 'Nutrition Management' : 'Ayurcare Management'
  const action = nutrition ? 'New assessment' : 'New treatment'
  const rows = nutrition ? nutritionRows : ayurRows
  const [query, setQuery] = useState('')
  const [editor, setEditor] = useState(false)
  const [selected, setSelected] = useState<(typeof rows)[number] | null>(null)
  const filtered = rows.filter((row) => `${row.mr} ${row.name} ${row.phone}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="mx-auto max-w-[1600px] space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wider text-primary">Clinical Care</p><h1 className="mt-1 font-display text-2xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{nutrition ? 'Assess nutrition outcomes, document diet plans, and review progress.' : 'Manage Ayurvedic treatment plans, therapies, and clinical follow-up.'}</p></div><div className="flex gap-2"><Button size="sm" variant="outline"><Printer className="mr-2 size-4"/>Print</Button><Button size="sm" variant="outline"><Download className="mr-2 size-4"/>Export</Button><Button size="sm" onClick={() => { setSelected(null); setEditor(true) }}><Plus className="mr-2 size-4"/>{action}</Button></div></div><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Card className="rounded-lg shadow-sm"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>{nutrition ? 'Assessments' : 'Treatment plans'}</CardTitle><CardDescription>Click a patient to review or update clinical care.</CardDescription></div><div className="relative"><Search className="absolute left-2.5 top-2 size-4 text-muted-foreground"/><Input className="w-56 pl-8" placeholder="Search MR or patient" value={query} onChange={(e) => setQuery(e.target.value)}/></div></CardHeader><CardContent className="px-0"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead className="border-y bg-muted/40 text-xs text-muted-foreground"><tr>{['Patient','Phone','Program / Treatment','Clinician','Review date','Status'].map((h) => <th key={h} className="px-5 py-3 text-left font-medium">{h}</th>)}</tr></thead><tbody>{filtered.map((row) => <tr key={row.mr} onClick={() => setSelected(row)} className="cursor-pointer border-b hover:bg-muted/50"><td className="px-5 py-4"><p className="font-medium">{row.name}</p><p className="text-xs text-primary">{row.mr}</p></td><td className="px-5 py-4 text-muted-foreground">{row.phone}</td><td className="px-5 py-4">{row.plan}</td><td className="px-5 py-4 text-muted-foreground">{row.clinician}</td><td className="px-5 py-4">{row.review}</td><td className="px-5 py-4"><span className="rounded-md bg-primary/10 px-2 py-1 text-xs font-medium text-primary">{row.status}</span></td></tr>)}</tbody></table></div></CardContent></Card><CareSummary selected={selected} nutrition={nutrition} onNew={() => setEditor(true)}/></div>{editor && <CareEditor nutrition={nutrition} patient={selected} onClose={() => setEditor(false)}/>}</div>
}

function CareSummary({ selected, nutrition, onNew }: { selected: (typeof nutritionRows)[number] | null; nutrition: boolean; onNew: () => void }) { return <Card className="h-fit rounded-lg shadow-sm"><CardHeader><CardTitle>{selected ? selected.name : 'Patient summary'}</CardTitle><CardDescription>{selected ? `${selected.mr} · ${selected.phone}` : 'Select a patient or start a new record.'}</CardDescription></CardHeader><CardContent>{selected ? <div className="space-y-4"><dl className="space-y-3 text-sm"><Pair label={nutrition ? 'Program' : 'Treatment plan'} value={selected.plan}/><Pair label={nutrition ? 'Dietitian' : 'Practitioner'} value={selected.clinician}/><Pair label="Review date" value={selected.review}/><Pair label="Status" value={selected.status}/></dl><div className="border-t pt-4"><p className="mb-2 text-xs font-medium text-muted-foreground">Previous care</p><div className="rounded-lg bg-muted p-3 text-sm"><p className="font-medium">Initial consultation</p><p className="mt-1 text-xs text-muted-foreground">02 Jun 2026 · Clinical notes recorded</p></div></div><Button className="w-full" size="sm" onClick={onNew}><Pencil className="mr-2 size-4"/>Edit record</Button></div> : <div className="py-6 text-center"><p className="text-sm text-muted-foreground">No patient selected.</p><Button className="mt-4" size="sm" onClick={onNew}><Plus className="mr-2 size-4"/>Create record</Button></div>}</CardContent></Card> }
function Pair({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-medium">{value}</dd></div> }
function CareEditor({ nutrition, patient, onClose }: { nutrition: boolean; patient: (typeof nutritionRows)[number] | null; onClose: () => void }) { const [saved, setSaved] = useState(false); const fields = nutrition ? ['Assessment date','Program','Weight','BMI','Body fat','Review date','Dietitian'] : ['Diagnosis','Treatment plan','Medicines','Procedures','Therapies','Practitioner','Review date']; return <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/20 p-4"><Card className="max-h-[90svh] w-full max-w-3xl overflow-y-auto rounded-lg shadow-xl"><CardHeader className="flex-row justify-between"><div><CardTitle>{nutrition ? 'Nutrition assessment' : 'Ayurcare treatment plan'}</CardTitle><CardDescription>{patient ? `${patient.name} · ${patient.mr}` : 'Enter an MR number to begin a new clinical record.'}</CardDescription></div><Button variant="ghost" size="icon-sm" onClick={onClose} aria-label="Close editor"><X className="size-4"/></Button></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Label className="text-xs text-muted-foreground">MR number</Label><div className="mt-1.5 flex gap-2"><Input defaultValue={patient?.mr} placeholder={nutrition ? 'NU000001' : 'AY000001'}/><Button variant="outline" size="sm">Fetch patient</Button></div></div>{fields.map((field) => <div key={field}><Label className="text-xs text-muted-foreground">{field}</Label><Input className="mt-1.5" type={field.includes('date') ? 'date' : 'text'} defaultValue={field === 'Program' || field === 'Treatment plan' ? patient?.plan : field === 'Dietitian' || field === 'Practitioner' ? patient?.clinician : ''}/></div>)}<div className="md:col-span-2"><Label className="text-xs text-muted-foreground">{nutrition ? 'Diet plan, observations, recommendations and notes' : 'Advice and clinical notes'}</Label><Textarea className="mt-1.5 min-h-36" placeholder="Document clinical observations and recommendations..."/></div><div className="md:col-span-2 flex justify-between border-t pt-4"><Button variant="outline" onClick={() => alert('Record removed from this local UI session.')}><Trash2 className="mr-2 size-4"/>Delete</Button><div className="flex gap-2"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={() => { setSaved(true); setTimeout(onClose, 500) }}>{saved ? 'Saved' : patient ? 'Update' : 'Save'}</Button></div></div></CardContent></Card></div> }
