'use client'

import { useMemo, useState } from 'react'
import { BarChart3, CalendarPlus, Check, Download, FileText, Filter, Plus, Printer, Search, Settings2, SlidersHorizontal, Stethoscope, UserRound, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Textarea } from '@/components/ui/textarea'
import { cn } from '@/lib/utils'

type Mode = 'patients' | 'visits' | 'consultations' | 'nutrition' | 'ayurcare' | 'followups' | 'billing' | 'settings' | 'reports'
type Row = { id: string; name: string; detail: string; date: string; status: string; amount?: string }

const definitions: Record<Mode, { title: string; description: string; action: string; columns: string[]; rows: Row[] }> = {
  patients: { title: 'Patient Directory', description: 'Search and manage active outpatient medical records.', action: 'Register patient', columns: ['MR number', 'Patient', 'Contact', 'Last visit', 'Status'], rows: [{id:'MR000001',name:'Aarav Sharma',detail:'98450 12345 · Male, 34',date:'02 Jun 2026',status:'Active'},{id:'MR000002',name:'Priya Nair',detail:'99860 45678 · Female, 28',date:'21 May 2026',status:'Active'},{id:'MR000003',name:'Rohan Mehta',detail:'90080 33221 · Male, 45',date:'30 May 2026',status:'Follow-up'}] },
  visits: { title: 'Visit Management', description: 'Track registrations, queues, and consultation progress.', action: 'New visit', columns: ['OP number', 'Patient', 'Department', 'Time', 'Status'], rows: [{id:'OP-260711-014',name:'Aarav Sharma',detail:'Nutrition Center',date:'09:30 AM',status:'In consultation'},{id:'OP-260711-015',name:'Meera Joseph',detail:'Ayurcare Center',date:'10:00 AM',status:'Waiting'},{id:'OP-260711-016',name:'Priya Nair',detail:'Nutrition Center',date:'10:30 AM',status:'Completed'}] },
  consultations: { title: 'Consultations', description: 'Clinical workspace for outpatient encounters.', action: 'Start consultation', columns: ['OP number', 'Patient', 'Clinician', 'Chief concern', 'Status'], rows: [{id:'OP-260711-014',name:'Aarav Sharma',detail:'Dr. Neha Verma',date:'Diet review',status:'In progress'},{id:'OP-260711-011',name:'Rohan Mehta',detail:'Dr. Arjun Das',date:'Wellness consultation',status:'Signed'}] },
  nutrition: { title: 'Nutrition Care', description: 'Nutrition assessments, diet plans, and follow-up outcomes.', action: 'New assessment', columns: ['Patient', 'Program', 'Dietitian', 'Review date', 'Status'], rows: [{id:'MR000001',name:'Aarav Sharma',detail:'Diabetes nutrition plan',date:'16 Jul 2026',status:'Due'},{id:'MR000002',name:'Priya Nair',detail:'Weight management',date:'18 Jul 2026',status:'Active'}] },
  ayurcare: { title: 'Ayurcare', description: 'Ayurvedic consultations, therapies, and treatment programs.', action: 'New treatment', columns: ['Patient', 'Treatment plan', 'Practitioner', 'Next session', 'Status'], rows: [{id:'MR000003',name:'Rohan Mehta',detail:'Panchakarma program',date:'14 Jul 2026',status:'Active'},{id:'MR000004',name:'Anjali Menon',detail:'Herbal therapy',date:'17 Jul 2026',status:'Planned'}] },
  followups: { title: 'Follow-ups', description: 'Review scheduled care and contact patients due today.', action: 'Schedule follow-up', columns: ['Patient', 'Program', 'Due date', 'Assigned to', 'Status'], rows: [{id:'FU-2021',name:'Aarav Sharma',detail:'Diet review',date:'Today, 03:30 PM',status:'Due today'},{id:'FU-2022',name:'Rohan Mehta',detail:'Therapy review',date:'14 Jul 2026',status:'Scheduled'}] },
  billing: { title: 'Billing Centre', description: 'Create invoices, record payments, and monitor receivables.', action: 'Create invoice', columns: ['Invoice', 'Patient', 'Service', 'Invoice date', 'Balance'], rows: [{id:'INV-90112',name:'Aarav Sharma',detail:'Nutrition consultation',date:'02 Jun 2026',status:'Pending',amount:'Rs. 1,800'},{id:'INV-90230',name:'Rohan Mehta',detail:'Ayurcare package',date:'30 May 2026',status:'Pending',amount:'Rs. 8,900'},{id:'INV-90301',name:'Priya Nair',detail:'Diet review',date:'21 May 2026',status:'Paid',amount:'Rs. 0'}] },
  settings: { title: 'Administration', description: 'Configure clinic operations, users, services, and print templates.', action: 'Add record', columns: ['Configuration', 'Category', 'Last updated', 'Updated by', 'Status'], rows: [{id:'CFG-001',name:'MediCare Hospital',detail:'Clinic information',date:'11 Jul 2026',status:'Published'},{id:'CFG-012',name:'Dr. Neha Verma',detail:'Doctors',date:'10 Jul 2026',status:'Active'},{id:'CFG-024',name:'Nutrition consultation',detail:'Billing items',date:'09 Jul 2026',status:'Active'}] },
  reports: { title: 'Reports & Analytics', description: 'Review operational performance by date, service, and centre.', action: 'Generate report', columns: ['Report', 'Period', 'Prepared on', 'Format', 'Status'], rows: [{id:'RPT-0711',name:'Daily revenue report',detail:'11 Jul 2026',date:'11 Jul 2026',status:'Ready'},{id:'RPT-0701',name:'Monthly patient growth',detail:'Jul 2026',date:'01 Jul 2026',status:'Ready'}] },
}

export function OperationsWorkspace({ mode }: { mode: Mode }) {
  const config = definitions[mode]
  const [query, setQuery] = useState('')
  const [editor, setEditor] = useState(false)
  const [selected, setSelected] = useState<Row | null>(null)
  const [saved, setSaved] = useState(false)
  const rows = useMemo(() => config.rows.filter((row) => `${row.id} ${row.name} ${row.detail}`.toLowerCase().includes(query.toLowerCase())), [config.rows, query])
  const report = mode === 'reports'
  const admin = mode === 'settings'
  return <div className="mx-auto max-w-[1600px] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wider text-primary">Operations</p><h1 className="mt-1 font-display text-2xl font-semibold">{config.title}</h1><p className="mt-1 text-sm text-muted-foreground">{config.description}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => window.print()}><Printer className="mr-2 size-4"/>Print</Button><Button variant="outline" size="sm" onClick={() => alert('Export prepared for the selected date range.')}><Download className="mr-2 size-4"/>Export</Button><Button size="sm" onClick={() => { setEditor(true); setSaved(false) }}><Plus className="mr-2 size-4"/>{config.action}</Button></div></div>
    {(report || mode === 'billing' || mode === 'visits') && <Summary mode={mode}/>} 
    <div className={cn('grid gap-6', selected && 'xl:grid-cols-[1fr_360px]')}><Card className="rounded-lg shadow-sm"><CardHeader className="gap-4 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>{report ? 'Published reports' : admin ? 'System configuration' : 'Workspace records'}</CardTitle><CardDescription>{rows.length} records shown</CardDescription></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-2.5 top-2 size-4 text-muted-foreground"/><Input className="w-56 pl-8" placeholder="Search records" value={query} onChange={(e) => setQuery(e.target.value)}/></div><Button size="icon-sm" variant="outline" aria-label="Filter records"><Filter className="size-4"/></Button></div></CardHeader><CardContent className="px-0"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y bg-muted/40 text-xs text-muted-foreground"><tr>{config.columns.map((column) => <th className="px-5 py-3 font-medium" key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id} onClick={() => setSelected(row)} className="cursor-pointer border-b transition-colors hover:bg-muted/50"><td className="px-5 py-4 font-medium text-primary">{row.id}</td><td className="px-5 py-4"><p className="font-medium text-foreground">{row.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{row.detail}</p></td><td className="px-5 py-4 text-muted-foreground">{row.detail}</td><td className="px-5 py-4 text-muted-foreground">{row.date}</td><td className="px-5 py-4"><span className={cn('rounded-md px-2 py-1 text-xs font-medium', row.status === 'Paid' || row.status === 'Active' || row.status === 'Ready' || row.status === 'Signed' ? 'bg-primary/10 text-primary' : 'bg-amber-100 text-amber-800')}>{row.amount ?? row.status}</span></td></tr>)}</tbody></table></div></CardContent></Card>{selected && <DetailPanel row={selected} mode={mode} onClose={() => setSelected(null)} />}</div>
    {admin && <SettingsSections/>}
    {editor && <Editor title={config.action} onClose={() => setEditor(false)} saved={saved} onSave={() => { setSaved(true); setTimeout(() => setEditor(false), 600) }} />}
  </div>
}

function Summary({ mode }: { mode: Mode }) { const values = mode === 'reports' ? [['Revenue','Rs. 4,82,600'],['Registrations','128'],['Visits','214'],['Pending bills','Rs. 48,750']] : mode === 'billing' ? [['Today invoices','18'],['Collected','Rs. 32,450'],['Outstanding','Rs. 48,750'],['Payments','24']] : [['Today visits','26'],['Waiting','8'],['In consultation','11'],['Completed','7']]; return <div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{values.map(([label,value]) => <Card key={label} className="rounded-lg shadow-sm"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p><p className="mt-2 text-xs text-primary">Current period</p></CardContent></Card>)}</div> }
function DetailPanel({ row, mode, onClose }: { row: Row; mode: Mode; onClose: () => void }) { return <Card className="h-fit rounded-lg shadow-sm"><CardHeader className="flex-row justify-between"><div><CardTitle className="text-base">{row.name}</CardTitle><CardDescription>{row.id}</CardDescription></div><Button variant="ghost" size="icon-sm" aria-label="Close details" onClick={onClose}><X className="size-4"/></Button></CardHeader><CardContent><Tabs defaultValue="summary"><TabsList className="w-full"><TabsTrigger value="summary">Summary</TabsTrigger><TabsTrigger value="notes">Notes</TabsTrigger></TabsList><TabsContent value="summary" className="pt-4"><dl className="space-y-3 text-sm"><Pair label="Reference" value={row.id}/><Pair label="Service / programme" value={row.detail}/><Pair label="Scheduled" value={row.date}/><Pair label="Current status" value={row.status}/></dl><Button className="mt-6 w-full" size="sm"><FileText className="mr-2 size-4"/>{mode === 'billing' ? 'Open invoice' : 'Open record'}</Button></TabsContent><TabsContent value="notes" className="pt-4"><Textarea placeholder="Add internal note" className="min-h-32"/><Button className="mt-3" size="sm">Save note</Button></TabsContent></Tabs></CardContent></Card> }
function Pair({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-medium">{value}</dd></div> }
function Editor({ title, onClose, onSave, saved }: { title: string; onClose: () => void; onSave: () => void; saved: boolean }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/20 p-4"><Card className="w-full max-w-2xl rounded-lg shadow-xl"><CardHeader className="flex-row justify-between"><div><CardTitle>{title}</CardTitle><CardDescription>Complete the required details and save the record.</CardDescription></div><Button size="icon-sm" variant="ghost" aria-label="Close editor" onClick={onClose}><X className="size-4"/></Button></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><EditorField label="Patient / record name"/><EditorField label="Department or service"/><EditorField label="Date" type="date"/><EditorField label="Assigned clinician"/><div className="sm:col-span-2"><Label className="text-xs text-muted-foreground">Notes</Label><Textarea className="mt-1.5 min-h-28" placeholder="Clinical or administrative details"/></div><div className="sm:col-span-2 flex justify-end gap-2 border-t pt-4"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={onSave}>{saved ? <Check className="mr-2 size-4"/> : null}{saved ? 'Saved' : 'Save record'}</Button></div></CardContent></Card></div> }
function EditorField({ label, type = 'text' }: { label: string; type?: string }) { return <div><Label className="text-xs text-muted-foreground">{label}</Label><Input className="mt-1.5" type={type}/></div> }
function SettingsSections() { const sections = [['Clinic information','Identity, addresses, contacts and operating hours'],['Doctors & dietitians','Clinical staff, specialties and schedules'],['Services & billing items','Consultation services, procedures, medicines and fees'],['Taxes & payment methods','Tax rules, cash, UPI, card and bank settings'],['Users & roles','Access permissions and account status'],['Print templates','Registration sheets, prescriptions and receipts'],['Backup & restore','Local data export and import settings']]; return <Card className="rounded-lg shadow-sm"><CardHeader><CardTitle>Administration areas</CardTitle><CardDescription>Open an area to review and update its local configuration.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{sections.map(([title, description]) => <button key={title} className="flex items-start gap-3 rounded-lg border p-4 text-left hover:bg-muted/50"><Settings2 className="mt-0.5 size-4 text-primary"/><span><span className="block font-medium">{title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{description}</span></span></button>)}</CardContent></Card> }
