'use client'

import { useState } from 'react'
import { DatabaseBackup, FileText, ImageUp, Plus, RotateCcw, Save, Settings2, ShieldCheck, Users, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

const areas = [
  {id:'clinic',title:'Clinic Information',description:'Identity, address, contacts and operating hours',icon:Settings2},
  {id:'staff',title:'Doctors & Dietitians',description:'Clinical staff, specialties and schedules',icon:Users},
  {id:'services',title:'Services & Billing Items',description:'Consultations, procedures, packages and charges',icon:FileText},
  {id:'taxes',title:'Taxes & Payment Methods',description:'Tax rules and payment channels',icon:ShieldCheck},
  {id:'users',title:'Users & Roles',description:'User accounts and access permissions',icon:Users},
  {id:'templates',title:'Logo & Print Templates',description:'Clinic logo, prescription and invoice layouts',icon:ImageUp},
  {id:'backup',title:'Backup & Restore',description:'Export and restore local clinic data',icon:DatabaseBackup},
]
export function SettingsWorkspace() {
 const [active, setActive] = useState(areas[0])
 const [saved, setSaved] = useState(false)
 const Icon = active.icon
 return <div className="mx-auto max-w-[1600px] space-y-6"><div><p className="text-xs font-medium uppercase tracking-wider text-primary">Administration</p><h1 className="mt-1 font-display text-2xl font-semibold">Settings</h1><p className="mt-1 text-sm text-muted-foreground">Configure clinic operations, staff access, services, print assets, and local maintenance.</p></div><div className="grid gap-6 xl:grid-cols-[300px_1fr]"><Card className="h-fit rounded-lg shadow-sm"><CardContent className="p-2">{areas.map((area) => { const AreaIcon = area.icon; return <button key={area.id} onClick={() => { setActive(area); setSaved(false) }} className={`flex w-full items-start gap-3 rounded-lg p-3 text-left ${active.id === area.id ? 'bg-primary/10 text-primary' : 'hover:bg-muted'}`}><AreaIcon className="mt-0.5 size-4 shrink-0"/><span><span className="block text-sm font-medium">{area.title}</span><span className="mt-1 block text-xs leading-4 text-muted-foreground">{area.description}</span></span></button> })}</CardContent></Card><Card className="rounded-lg shadow-sm"><CardHeader className="flex-row items-start justify-between border-b"><div className="flex gap-3"><div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary"><Icon className="size-4"/></div><div><CardTitle>{active.title}</CardTitle><CardDescription>{active.description}</CardDescription></div></div>{active.id !== 'backup' && <Button size="sm" onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 1200) }}><Save className="mr-2 size-4"/>{saved ? 'Saved' : 'Save changes'}</Button>}</CardHeader><CardContent className="pt-5"><SettingsPanel id={active.id}/></CardContent></Card></div></div>
}
function SettingsPanel({ id }: { id: string }) { if (id === 'backup') return <div className="grid gap-5 md:grid-cols-2"><ActionCard title="Create backup" description="Export current clinic records and configuration to a local archive." action="Create backup" icon={DatabaseBackup}/><ActionCard title="Restore backup" description="Choose a previously created archive to restore clinic records." action="Select backup" icon={RotateCcw}/></div>; if (id === 'templates') return <div className="grid gap-5 md:grid-cols-2"><ActionCard title="Clinic logo" description="Upload a logo used on prescriptions, invoices, and reports." action="Upload logo" icon={ImageUp}/><ActionCard title="Print templates" description="Choose the professional A4 layout used for clinical documents." action="Manage templates" icon={FileText}/></div>; const names: Record<string,string[]> = {clinic:['Clinic name','Address','District','State','PIN code','Primary phone'],staff:['Staff name','Specialty','Registration number','Mobile number'],services:['Service name','Category','Default rate','Tax rate'],taxes:['Tax name','Rate (%)','Payment method','Account reference'],users:['User name','Email address','Role','Account status']}; return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-2">{(names[id] ?? []).map((label) => <div key={label}><Label className="text-xs text-muted-foreground">{label}</Label><Input className="mt-1.5" placeholder={label}/></div>)}</div><div className="rounded-lg border"><div className="flex items-center justify-between border-b p-4"><div><p className="font-medium">Configured records</p><p className="text-xs text-muted-foreground">Maintain active configuration entries for this area.</p></div><Button variant="outline" size="sm"><Plus className="mr-2 size-4"/>Add record</Button></div><div className="p-4 text-sm text-muted-foreground">No additional records have been added in this UI session.</div></div></div> }
function ActionCard({ title, description, action, icon: Icon }: { title: string; description: string; action: string; icon: typeof DatabaseBackup }) { return <Card className="rounded-lg border shadow-none"><CardContent className="p-5"><Icon className="size-5 text-primary"/><p className="mt-4 font-medium">{title}</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{description}</p><Button className="mt-5" variant="outline" size="sm">{action}</Button></CardContent></Card> }
